### ISSUE TITLE
Rename the master branch to main

### ISSUE THREAD

**Issue by TatoExp** [char/blm-instagram-bot#29]
The term "master" has racist and negative connotations leading back to slavery, which undermines the efforts of this repository. (See: https://www.bbc.com/news/technology-53050955)

Because of this I believe that we should rename the master branch to main, so that we may continue to make black people feel comfortable in this community.

**Comment by voidstar0** [comment]
Good catch! This repo was created before this was the default on GitHub and so it slipped my mind. Will fix this once I get home

**Comment by voidstar0** [comment]
All done!
