### ISSUE TITLE
#BlackoutTuesday getting merged into #BlackLivesMatter?

### ISSUE THREAD

**Issue by htried** [char/blm-instagram-bot#3]
I've heard some anecdotal reports that Instagram is merging the two hashtags. Does it make sense to change the script of the comment to urge people to post links to local bail funds, mutual aid organizations, protest groups, NAACP chapters, etc?

**Comment by user24** [comment]
Can you do some research and see if there is evidence the hashtags are getting merged?

**Comment by htried** [comment]
Did a bit of digging and found a couple of posts with just #BlackoutTuesday that were under the BLM hashtag, but not many. It's something that people in my circles are writing on social media but it could also be the result of people changing their captions and the image still circulating under the original hashtag. Probably not an issue on Instagram's side of things.

**Comment by syntax** [comment]
i can only assume this is due to people at one point having the blm hastag and then editing the caption to be #BlackoutTuesday after being told by friends/ consideration they need to change, as this (editing the caption) does not alter the collective hashtags the post still resides in.
